# Generated by Django 3.0.7 on 2020-06-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assignments', models.ManyToManyField(default='', to='api.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='DefFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ion_user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('git', models.URLField(default='')),
                ('classes', models.ManyToManyField(default='', to='api.Classes')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_id', models.IntegerField()),
                ('ion_user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('webmail', models.EmailField(blank=True, max_length=254)),
                ('grade', models.IntegerField()),
                ('git', models.URLField()),
                ('repo', models.URLField(default='')),
                ('classes', models.ManyToManyField(default='', to='api.Classes')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='files',
            field=models.ManyToManyField(default='instructions.txt', to='api.DefFiles'),
        ),
    ]
