# Generated by Django 3.0.7 on 2020-06-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
