# Generated by Django 3.0.7 on 2020-06-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='ion_user',
            field=models.CharField(default='eharris1', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
