# Generated by Django 3.0.7 on 2020-06-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='webmail',
        ),
        migrations.AddField(
            model_name='classes',
            name='confirmed',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='classes',
            name='unconfirmed',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='added_to',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='completed',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='files',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='repo',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
