# Generated by Django 3.0.7 on 2020-06-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='class',
            name='confirmed',
            field=models.ManyToManyField(blank=True, related_name='confirmed', to='api.Student'),
        ),
        migrations.RemoveField(
            model_name='class',
            name='unconfirmed',
        ),
        migrations.AddField(
            model_name='class',
            name='unconfirmed',
            field=models.ManyToManyField(blank=True, related_name='unconfirmed', to='api.Student'),
        ),
    ]
