# Generated by Django 3.0.7 on 2020-06-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='path',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
