# Generated by Django 3.0.7 on 2020-06-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='files',
            field=models.ManyToManyField(to='api.DefFiles'),
        ),
    ]
