# Generated by Django 3.0.7 on 2020-06-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200607_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='repo',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='files',
            field=models.ManyToManyField(default='', to='api.DefFiles'),
        ),
    ]
