# Generated by Django 3.0.7 on 2020-06-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200615_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='teacher', to='api.Class'),
        ),
    ]
