# Generated by Django 3.0.7 on 2020-06-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200609_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='repo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='webmail',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
