# Generated by Django 3.0.7 on 2020-06-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200606_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='webmail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
