# Generated by Django 3.0.7 on 2020-06-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200612_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='assignments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classes',
            name='default_file',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='classes',
            name='repo',
            field=models.URLField(blank=True, default=''),
        ),
    ]
