# Generated by Django 3.0.7 on 2020-06-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200614_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
