# Generated by Django 3.0.7 on 2020-06-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200607_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='git',
            field=models.CharField(default='', max_length=100),
        ),
    ]
