# Generated by Django 3.0.7 on 2020-06-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200609_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='added_to',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
