# Generated by Django 3.0.7 on 2020-06-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200614_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='ion_user',
            field=models.CharField(default='2022rkhondak', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
