# Generated by Django 3.0.7 on 2020-06-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_added_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed',
            field=models.TextField(blank=True, default=''),
        ),
    ]
