# Generated by Django 3.0.7 on 2020-06-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200608_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='git',
            field=models.CharField(max_length=100),
        ),
    ]
