# Generated by Django 3.0.7 on 2020-06-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_student_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='confirmed',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='classes',
            name='unconfirmed',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='repo',
            field=models.URLField(blank=True, default=''),
        ),
    ]
