# Generated by Django 3.0.7 on 2020-06-06 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200606_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Classes'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
    ]
