# Generated by Django 3.0.7 on 2020-06-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200606_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='students',
        ),
    ]
