# Generated by Django 3.0.7 on 2020-06-08 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200608_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='default_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DefFiles'),
        ),
    ]
