# Generated by Django 3.0.7 on 2020-06-06 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200606_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='teachers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Teacher'),
        ),
    ]
