# Generated by Django 3.0.7 on 2020-06-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_classes_default_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='default_file',
        ),
        migrations.AddField(
            model_name='classes',
            name='default_file',
            field=models.ManyToManyField(to='api.DefFiles'),
        ),
    ]
