# Generated by Django 3.0.7 on 2020-06-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200606_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='teachers',
        ),
        migrations.AddField(
            model_name='student',
            name='assignments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Assignment'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Classes'),
        ),
    ]
