# Generated by Django 3.0.7 on 2020-06-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200608_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=100, primary_key=False, serialize=False),
        ),
    ]
