# Generated by Django 3.0.7 on 2020-06-06 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200606_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='url',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='url',
        ),
        migrations.RemoveField(
            model_name='student',
            name='url',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='url',
        ),
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Classes'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
    ]
