# Generated by Django 3.0.7 on 2020-06-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200608_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='files',
            field=models.ManyToManyField(to='api.DefFiles'),
        ),
    ]
