# Generated by Django 3.0.7 on 2020-06-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200608_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='deffiles',
            name='path',
            field=models.FilePathField(default=''),
        ),
    ]
