# Generated by Django 3.0.7 on 2020-06-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_classes_assignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='assignments',
        ),
    ]
