# Generated by Django 3.0.7 on 2020-06-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_deffiles_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deffiles',
            name='path',
            field=models.CharField(default='', max_length=100),
        ),
    ]
