# Generated by Django 3.0.7 on 2020-06-06 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_student_assignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='assignments',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='students',
        ),
        migrations.AddField(
            model_name='assignment',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Classes'),
        ),
    ]
