# Generated by Django 3.0.7 on 2020-06-06 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200606_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='teachers',
        ),
        migrations.AddField(
            model_name='assignment',
            name='students',
            field=models.ManyToManyField(default='', through='api.Classes', to='api.Student'),
        ),
        migrations.AddField(
            model_name='classes',
            name='assignments',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Assignment'),
        ),
    ]
