# Generated by Django 3.0.7 on 2020-06-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200608_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='path',
            field=models.CharField(default='', max_length=100),
        ),
    ]
