# Generated by Django 3.0.7 on 2020-06-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_assignment_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='path',
            field=models.CharField(max_length=100),
        ),
    ]
