# Generated by Django 3.0.7 on 2020-06-06 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200606_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='teachers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Teacher'),
        ),
    ]
