# Generated by Django 3.0.7 on 2020-06-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_classes_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='students',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='assignments',
        ),
        migrations.AddField(
            model_name='classes',
            name='assignments',
            field=models.ManyToManyField(default='', to='api.Assignment'),
        ),
        migrations.RemoveField(
            model_name='classes',
            name='students',
        ),
        migrations.AddField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(null=True, to='api.Student'),
        ),
    ]
