# Generated by Django 3.0.7 on 2020-06-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200606_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(default='', to='api.Student'),
        ),
    ]
