# Generated by Django 3.0.7 on 2020-06-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200606_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='students',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='teachers',
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(default='', to='api.Classes'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(default='', to='api.Classes'),
        ),
    ]
