# Generated by Django 3.0.7 on 2020-06-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200614_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='grade',
            field=models.IntegerField(default=9),
        ),
    ]
